Pinscribe Project Assets/ProjectEnv/college_project/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

Pinscribe Project Assets/ProjectEnv/college_project/college_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Homepage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test',views.Testpage.as_view(),name='test'),
    path('thanks',views.Thankspage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('user/',include('user.urls',namespace='user')),
]

Pinscribe Project Assets/ProjectEnv/college_project/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('new',views.CreatePost.as_view(),name='create'),
    path('by/<username>',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<pk>',views.PostDetail.as_view(),name='single'),
]

Pinscribe Project Assets/ProjectEnv/college_project/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('home/',views.UserHomeView.as_view(),name='home'),
    path('<username>/update',views.UserProfileUpdateView.as_view(),name='update'),
]

Pinscribe Project Assets/ProjectEnv/college_project/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

Pinscribe Project Assets/ProjectEnv/college_project/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from user.models import Profile

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField(max_length=500)

    def __str__(self):
        return self.message[:30]

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("posts:single", kwargs={"username":self.user.username,
                        "pk": self.pk})
    
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

Pinscribe Project Assets/ProjectEnv/college_project/user/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.dispatch import receiver #add this
from django.db.models.signals import post_save

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='profile')
    first_name=models.CharField(max_length=30, null=True, blank=False)
    last_name=models.CharField(max_length=30, null=True, blank=False)
    email = models.EmailField(max_length=30, null=True, blank=True)
    image = models.ImageField(default='default.png', upload_to='profile_pics')

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


    def __str__(self):
        return f'{self.user.username} Profile' 
    
    def save(self, *args, **kwargs):
        super(Profile,self).save(*args, **kwargs)

        img = Image.open(self.image.path) # Open image

        # resize image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size) # Resize image
            img.save(self.image.path) # Save it again and override the larger image
    

Pinscribe Project Assets/ProjectEnv/college_project/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()
    
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attr={'help_test':''}

Pinscribe Project Assets/ProjectEnv/college_project/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


# Create a ProfileUpdateForm to update image.
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image','first_name','last_name','email']

Pinscribe Project Assets/ProjectEnv/college_project/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms
# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

Pinscribe Project Assets/ProjectEnv/college_project/college_project/views.py
from django.views.generic import TemplateView
from django.shortcuts import redirect
from user.views import UserHomeView

class Homepage(TemplateView):
    template_name = 'index.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('user:home')

class Testpage(TemplateView):
    template_name = 'test.html'

class Thankspage(TemplateView):
    template_name = 'thanks.html'

Pinscribe Project Assets/ProjectEnv/college_project/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import models
from . import forms

from django.contrib.auth import get_user_model
User = get_user_model()

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_posts.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user')

    def get_queryset(self):
        queryset = super().get_query()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):

    fields = ('message',)
    model = models.Post
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

Pinscribe Project Assets/ProjectEnv/college_project/user/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin

from django.urls  import reverse,reverse_lazy
from django.views import generic
from posts.models import Post
from .models import Profile
from django import forms
from .forms import ProfileUpdateForm
from django.contrib.auth.models import User

class UserHomeView(generic.ListView,LoginRequiredMixin):
    model = Post
    template_name = 'user/user_home.html'


class UserProfileUpdateView(generic.UpdateView,LoginRequiredMixin):
    model = Profile
    form_class = ProfileUpdateForm
    success_url = reverse_lazy('user:home')
    template_name = 'user/update_user_profile.html'

Pinscribe Project Assets/ProjectEnv/college_project/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-primary">
    </form>
</div>
{% endblock content %}

Pinscribe Project Assets/ProjectEnv/college_project/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-primary">
    </form>
</div>
{% endblock content %}

Pinscribe Project Assets/ProjectEnv/college_project/posts/templates/posts/_post.html
<div>
    <h3>{{post.message|safe}}</h3>
    <div>
        <strong>{{post.user.username}}</strong>
        <h5>
            <a href="{% url 'posts:for_user' username=post.user.username%}"></a>
        </h5>
        <time>
        <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}"></a>
        </time>
    </div>
</div>

Pinscribe Project Assets/ProjectEnv/college_project/posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}
    <div>
        {% block prepost %}{% endblock prepost %}
        {% block post_content %}{% endblock post_content %}
        {% block post_post %}{% endblock post_post %}
    </div>
{% endblock content %}

Pinscribe Project Assets/ProjectEnv/college_project/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<div>
    {% include "posts/_post.html" %}
</div>
{% endblock post_content %}

Pinscribe Project Assets/ProjectEnv/college_project/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}

{% block post_content %}
    <h4>Create a new Post</h4>
    <form action="{% url 'posts:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Post" class="btn btn-primary">
    </form>
{% endblock post_content %}

Pinscribe Project Assets/ProjectEnv/college_project/posts/templates/posts/user_posts.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
    <div>
        <h1>@{{post_user.username}}</h1>
    </div>
{% endblock prepost %}

{% block post_content %}
    <div>
        {% for post in post_list %}
        {% include "posts/_posts.html" %}
        {% endfor %}
    </div>
{% endblock post_content %}

Pinscribe Project Assets/ProjectEnv/college_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pinscribe</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
     
</head>
<body>

    <nav>
        <div>
            <img src="{% static 'images/logo.png' %}" alt="logo">

            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% comment %} redirect user {% endcomment %}
                {% else %}
                <li><a href="">About Us</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div>
        
        <h1>Welcome to Pinscribe!</h1>
        {% block content %}{% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>

</html>

Pinscribe Project Assets/ProjectEnv/college_project/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h3>Home Page</h3>
{% endblock content %}

Pinscribe Project Assets/ProjectEnv/college_project/templates/test.html
{% extends 'base.html' %}

{% block content %}
    <h1>You are now logged in !!!</h1>
{% endblock content %}

Pinscribe Project Assets/ProjectEnv/college_project/templates/thanks.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thank You for visiting.</h1>
    <h1>You have succesfully logged out!!</h1> 
{% endblock content %}

Pinscribe Project Assets/ProjectEnv/college_project/user/templates/user/update_user_profile.html
{% extends 'user/user_base.html' %}
{% load bootstrap5 %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update">
    </form>
{% endblock content %}

Pinscribe Project Assets/ProjectEnv/college_project/user/templates/user/user_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pinscribe</title>
</head>
<body>

    <nav>
        <div>
            <img src="{% static 'images/logo.png' %}" alt="logo">

            <ul>
                <li><a href="{% url 'user:home' %}">Home</a></li>
                <li><a href="{% url 'user:update' username=user.username %}">Profile</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
        </div>
    </nav>

    <div>
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

Pinscribe Project Assets/ProjectEnv/college_project/user/templates/user/user_home.html
{% extends 'user/user_base.html' %}
{% load bootstrap5 %}

{% block content %}
    {% for post in posts_list %}
        {{post.as_p}}
        <p>Content her</p>
    {% endfor %}
{% endblock content %}

Pinscribe Project Assets/ProjectEnv/college_project/user/templates/user/user_profile.html
{% extends 'user/user_base.html' %}
{% load bootstrap5 %}

{% block content %}
    {{object.username}}
{% endblock content %}