Pinscribe Project Assets/ProjectEnv/project_pin/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('settings', views.settings, name='settings'),
    # path('upload', views.upload, name='upload'),
    path('follow', views.follow, name='follow'),
    path('search', views.SearchView.as_view(), name='search'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('like-post', views.like_post, name='like-post'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('create', views.create, name='create'),
    path('bookmark-post', views.bookmark_post, name='bookmark-post'),
    path('post/<post_id>',views.post_detail,name='post-detail'),
]

Pinscribe Project Assets/ProjectEnv/project_pin/notifications_app/urls.py
from django.urls import path
from .views import index,read_notification

app_name = "notifications"

urlpatterns = [
    path('',index,name='index'),
    path('read/<not_id>',read_notification,name='read'),
]

Pinscribe Project Assets/ProjectEnv/project_pin/project_pin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('notifications/',include('notifications_app.urls',namespace='notifiactions')),
    path('saved/',include('save_post_app.urls',namespace='saved')),
]

# Only add this when we are in debug mode.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pinscribe Project Assets/ProjectEnv/project_pin/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  {% block title %}
  <title>Base</title>
  {% endblock title %}

  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;900&family=Roboto:wght@100;900&display=swap" rel="stylesheet">
  

  <link href="{% static 'css/index.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/search.css' %}">


</head>

<body>
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>
    {% block header %}
    {% endblock header %}
    {% block main %}
    {% endblock main %}
    {% block bottom %}{% endblock bottom %}


    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'vendor/typed.js/typed.min.js' %}"></script>
    <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

    <script src="{% static 'js/index.js' %}"></script>
    {% block script %}{% endblock script %}
</body>

</html>

Pinscribe Project Assets/ProjectEnv/project_pin/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load social_share %}
{% block title %}
<title>Home</title>
{% endblock title %}

{% block header %}
<header id="header">
  <div class="d-flex flex-column">
    <div class="profile">
      <img src="{% static 'images/logo-text.png' %}" alt="" class="img-fluid rounded-circle">
    </div>

    <nav id="navbar" class="nav-menu navbar">
      <ul>
        <li><a href="{% url 'core:index' %}" class="nav-link scrollto active"><i class="bx bx-home"></i>
            <span>Home</span></a></li>
        <li><a href="{% url 'core:search' %}" class="nav-link scrollto"><i class="bx bx-search"></i>
            <span>Search</span></a></li>
        <li><a href="{% url 'notifications:index' %}" class="nav-link scrollto"><i class="bx bx-bell"></i> <span>Notifications</span></a></li>
        <li><a href="{% url 'saved:index' %}" class="nav-link scrollto"><i class="bx bx-bookmark"></i> <span>Saved Posts</span></a></li>
        <li><a href="{% url 'core:profile' pk=user_profile.user.username %}" class="nav-link scrollto"><i
              class="bx bx-user"></i> <span>Profile</span></a></li>
      </ul>
    </nav>
  </div>

  <div class='footer'>
    <button class='btn-more'><a href="{% url 'core:logout' %}" class='btn-more'><i class='bx bx-log-out'></i>
        Logout</a></button>
  </div>
</header>
{% endblock header %}

{% block main %}
<main id="main">
  <section class="search-btn">
    <a href="{% url 'core:search' %}"><button>
        <div><i class='bx bx-search' id='search-btn-logo'></i></div>
        <div>
          <p>Search</p>
        </div>
      </button></a>
  </section>

  {% comment %} <div class='sug-container'>
    <div>
      {% for suggestion in suggestions_username_profile_list %}
      <div class="sug-block">
        <div class="sug-data">
          <a href="/profile/{{suggestion.user}}">
            <img src="{{suggestion.profile_pic.url}}" class="sug-user-avatar">
          </a>
          <div class="sug-details">
            <span class="block capitalize font-semibold"> {{suggestion.user}} </span>
            <span class="block capitalize text-sm"> {{suggestion.bio}} </span>
          </div>
        </div>
        <a href="/profile/{{suggestion.user}}" class="sug-btn"> View User </a>
      </div>
      {% endfor %}
    </div>
  </div> {% endcomment %}

  <div class='body-body'>
    <div class="card" style="width: 60rem">
      <div>
        {% if not posts %}
        <p class='no-post-p'>No post here...</p>
        {% else %}
        {% for post in posts reversed %}
        <div class="d-flex p-3  d-flex-custom">
          <div class="d-flex ps-3">
            <div class='post-user'>
              <a href="{% url 'core:profile' pk=post.user %}">
                <h6 id="text-body">
                  {{post.author_name}}
                  <span class="small font-weight-normal">@{{post.user}}</span>
                  <span class="small font-weight-normal"> • </span>
                  <span class="small font-weight-normal">{{post.created_at}}</span>
                  <span><i class="fas fa-angle-down float-end"></i></span>
                </h6>
              </a>
              <p style="line-height: 1.2;">
                {{post.caption}}
              </p>
              <div class='post-bd'>
                <img src="{{post.image.url}}" class="img-fluid-custom rounded " alt="post img" />
              </div>
              <ul class="list-unstyled d-flex justify-content-between mb-0 ">
                <li><a href="/like-post?post_id={{post.id}}"><i id='icon' class='bx bxs-heart'></i><span
                      class="small ps-2">{{post.no_of_likes}}</span></a></li>
                <li><a href="saved/save?post_id={{post.id}}"><i id='icon' class='bx bxs-bookmark'></i></a></li>
                <li><a href="{{post.image.url}}" download><i id='icon' class='bx bxs-download'></i></a></li>
                <li>{% post_to_facebook object_or_url "<i id='icon' class='bx bxl-facebook'></i>" %}</li>
              </ul>
            </div>
          </div>
          <hr>
        </div>
        {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>

</main>
{% endblock main %}

{% block bottom %}
<a href="{% url 'core:create' %}" class="float">
  <i class="bx bx-plus my-float"></i></i>
</a>
{% endblock bottom %}

Pinscribe Project Assets/ProjectEnv/project_pin/templates/notif.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Notifications</title>
<link rel="stylesheet" href="{% static 'css/notif.css' %}">
{% endblock title %}

{% block header %}
<header id="header">
  <div class="d-flex flex-column">

    <div class="profile">
      <img src="{% static 'images/logo-text.png' %}" alt="" class="img-fluid rounded-circle">
    </div>

    <nav id="navbar" class="nav-menu navbar">
      <ul>
        <li><a href="{% url 'core:index' %}" class="nav-link scrollto"><i class="bx bx-home"></i> <span>Home</span></a>
        </li>
        <li><a href="{% url 'core:search' %}" class="nav-link scrollto"><i class="bx bx-search"></i>
            <span>Search</span></a></li>
        <li><a href="{% url 'notifications:index' %}" class="nav-link scrollto  active"><i class="bx bx-bell"></i> <span>Notifications</span></a></li>
        <li><a href="{% url 'saved:index' %}" class="nav-link scrollto"><i class="bx bx-bookmark"></i> <span>Saved Posts</span></a></li>
        <li><a href="{% url 'core:profile' pk=user_profile.user.username %}" class="nav-link scrollto"><i class="bx bx-user"></i>
            <span>Profile</span></a></li>
      </ul>
    </nav>
  </div>

  <div class='footer'>
    <a href="{% url 'core:logout' %}" class="btn-more nav-link"><i class="bx bx-log-out" id="more-btn-logo"></i><span>Logout</span></a>
  </div>
</header>
{% endblock header %}

{% block main %}
<main id="main">
  <div class='page-body'>
    <div class='content-header'>
      <p>Notifications</p>
    </div>
    <div class='content-body'>
      {% if not noti_list %}
      <div class='notification-block'>
        <marquee id='no-new-noti' scrollamount='10'; behavior="" direction="right">No new notifications :)</marquee>
      </div>
      {% else %}
      {% for noti in noti_list %}
      <div class='notification-block'>
        <div class='notification-block-left'>
          <i class='bx bxs-bell-ring'></i>
        </div>
        <div class='notification-block-middle'>
          <p>{{noti.message}}</p>
        </div>
        <div class='notification-block-right'>
          <a href="{% url 'notifications:read' not_id=noti.not_id %}"><i class='bx bx-x-circle'></i></a>
        </div>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</main>
{% endblock main %}

Pinscribe Project Assets/ProjectEnv/project_pin/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load social_share %}

{% block title %}
<title>Post Detail</title>
<link rel="stylesheet" href="{% static 'css/post_detail.css' %}">
{% endblock title %}

{% block header %}
{% endblock header %}

{% block main %}
<a id='x-btn' href="{% url 'saved:index' %}"><i class='bx bx-x'></i></a>
<div class='post-page-body'>
    <div class='post-body-left'>
        <img class='i-pbl' src="{{post.image.url}}" class="img-fluid-custom rounded " alt="post img" />
    </div>
    <div class='post-body-right'>
        <div class='post-body-right-top'>
            <ul class="list-unstyled d-flex justify-content-between mb-0 ">
                <li><a href="/like-post?post_id={{post.id}}"><i id='icon' class='bx bxs-heart'></i></a></li>
                <li><a href="saved/save?post_id={{post.id}}"><i id='icon' class='bx bxs-bookmark'></i></a></li>
                <li><a href="{{post.image.url}}" download><i id='icon' class='bx bxs-download'></i></a></li>
                <li>{% post_to_facebook object_or_url "<i id='icon' class='bx bxl-facebook'></i>" %}</li>
              </ul>
        </div>
        <div class='post-body-right-middle'>
            <p style="line-height: 1.2;">
                {{post.caption}}
              </p>
        </div>
        <div class='post-body-right-bottom'>
            <p class='pbrb-p'>Comments Coming Soon 👍</p>
            <div class='pbrb-div'>
                <input class='pbrb-inp' type="text" placeholder='Add a Comment'>
                <span class='pbrb-span'>😀</span>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

Pinscribe Project Assets/ProjectEnv/project_pin/templates/profile.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<title>Profile</title>
{% endblock title %}

{% block header %}
<header id="header">
  <div class="d-flex flex-column">

    <div class="profile">
      <img src="{% static 'images/logo-text.png' %}" alt="" class="img-fluid rounded-circle">
    </div>

    <nav id="navbar" class="nav-menu navbar">
      <ul>
        <li><a href="{% url 'core:index' %}" class="nav-link scrollto"><i class="bx bx-home"></i> <span>Home</span></a>
        </li>
        <li><a href="{% url 'core:search' %}" class="nav-link scrollto"><i class="bx bx-search"></i> <span>Search</span></a></li>
        <li><a href="{% url 'notifications:index' %}" class="nav-link scrollto"><i class="bx bx-bell"></i> <span>Notifications</span></a></li>
        <li><a href="{% url 'saved:index' %}" class="nav-link scrollto"><i class="bx bx-bookmark"></i> <span>Saved Posts</span></a></li>
        <li><a href="{% url 'core:profile' pk=user_profile.user.username %}" class="nav-link scrollto active"><i
              class="bx bx-user"></i> <span>Profile</span></a></li>
      </ul>
    </nav>
  </div>

  <div class='footer'>
    <a href="{% url 'core:logout' %}" class="btn-more nav-link"><i class="bx bx-log-out"
        id="more-btn-logo"></i><span>Logout</span></a>
  </div>
</header>
{% endblock header %}

{% block main %}
<main id="main">
  <section class="inner-page">
    <section class="h-100 gradient-custom-2">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-lg-9 col-xl-7">
            <div class="card">
              <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
                <div class="ms-4 mt-5 d-flex flex-column p-c-d" >
                  <img src="{{user_profile.profile_pic.url}}" alt="Generic placeholder image"
                    class="img-fluid img-thumbnail mt-4 mb-2 custom-profile-img" 
                    style="width: 200px; height: 200px; z-index: 1; object-fit: cover;object-position: top;">
                </div>
                <div class="ms-3" style="margin-top: 130px;">
                  <div class='user-name-data'>
                    {{user_profile.display_name}}
                    <br>
                    @{{user_profile.user.username}}
                  </div>
                </div>
                <form action="/follow" method="POST" class='follow-form'>
                  {% csrf_token %}
                  <input type="hidden" value="{{user.username}}" name="follower" />
                  <input type="hidden" value="{{user_object.username}}" name="user" />

                  {% if user_object.username == user.username %}
                  <a href="/settings"><p class='edit-btn'>Edit Profile</p></a>
                  {% else %}
                  <a data-ripple=""><button type="submit" id='f-unf-btn'>{{button_text}}</button></a>
                  {% endif %}
                </form>
              </div>
              <div class="p-4 text-black" style="background-color: #efe6ce;">
                <div class="d-flex justify-content-end text-center py-1">
                  <div>
                    <p class="mb-1 h5">{{user_post_length}}</p>
                    <p class="small text-muted mb-0">Posts</p>
                  </div>
                  <div class="px-3">
                    <p class="mb-1 h5">{{user_followers}}</p>
                    <p class="small text-muted mb-0">Followers</p>
                  </div>
                  <div>
                    <p class="mb-1 h5">{{user_following}}</p>
                    <p class="small text-muted mb-0">Following</p>
                  </div>
                </div>
              </div>
              <div class="card-body p-4 text-black">
                <div class="mb-5">
                  <p class="lead fw-normal mb-1">Bio</p>
                  <div class="p-4 bio-container" style="background-color: #efe6ce; border-radius:18px;">
                    <p class="font-italic mb-1">{{user_profile.bio}}</p>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center mb-4">
                  <p class="lead fw-normal mb-0">Recent posts</p>
                </div>
                <div class="post-grid">
                  {% for post in user_posts %}
                  <a  href="{{post.image.url}}" id='post'>
                    <img src="{{post.image.url}}" class='post'></a>
                  {% endfor %}
                </div>                
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </section>
</main>
{% endblock main %}

Pinscribe Project Assets/ProjectEnv/project_pin/templates/saved_posts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Saved Posts</title>
<link rel="stylesheet" href="{% static 'css/saved.css' %}">
{% endblock title %}

{% block header %}
<header id="header">
  <div class="d-flex flex-column">

    <div class="profile">
      <img src="{% static 'images/logo-text.png' %}" alt="" class="img-fluid rounded-circle">
    </div>

    <nav id="navbar" class="nav-menu navbar">
      <ul>
        <li><a href="{% url 'core:index' %}" class="nav-link scrollto"><i class="bx bx-home"></i> <span>Home</span></a>
        </li>
        <li><a href="{% url 'core:search' %}" class="nav-link scrollto"><i class="bx bx-search"></i>
            <span>Search</span></a></li>
        <li><a href="{% url 'notifications:index' %}" class="nav-link scrollto "><i class="bx bx-bell"></i> <span>Notifications</span></a></li>
        <li><a href="{% url 'saved:index' %}" class="nav-link scrollto active"><i class="bx bx-bookmark"></i> <span>Saved Posts</span></a></li>
        <li><a href="{% url 'core:profile' pk=user_profile.user.username %}" class="nav-link scrollto"><i class="bx bx-user"></i>
            <span>Profile</span></a></li>
      </ul>
    </nav>
  </div>

  <div class='footer'>
    <a href="{% url 'core:logout' %}" class="btn-more nav-link"><i class="bx bx-log-out" id="more-btn-logo"></i><span>Logout</span></a>
  </div>
</header>
{% endblock header %}

{% block main %}
<main id="main">
  <div class='page-body'>
    <div class='content-header'>
      <p>Saved Posts</p>
    </div>
    <div class='content-body'>
        {% if not saved_post_list %}
        <p>No saved posts -/(-_-)\-</p>
        {% else %}
        {% for entry in saved_post_list %}
        <div class='post-block'>
          <a href="{% url 'core:post-detail' post_id=entry.post.id %}">
              <img class='img' src="{{entry.post.image.url}}" alt="post image">
          </a>
        </div>
        {% endfor %}
        {% endif %}
    </div>
  </div>
</main>
{% endblock main %}

Pinscribe Project Assets/ProjectEnv/project_pin/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Search</title>
{% endblock title %}

{% block header %}
<header id="header">
  <div class="d-flex flex-column">

    <div class="profile">
      <img src="{% static 'images/logo-text.png' %}" alt="" class="img-fluid rounded-circle">
    </div>

    <nav id="navbar" class="nav-menu navbar">
      <ul>
        <li><a href="{% url 'core:index' %}" class="nav-link scrollto"><i class="bx bx-home"></i> <span>Home</span></a>
        </li>
        <li><a href="{% url 'core:search' %}" class="nav-link scrollto active"><i class="bx bx-search"></i>
            <span>Search</span></a></li>
        <li><a href="{% url 'notifications:index' %}" class="nav-link scrollto"><i class="bx bx-bell"></i> <span>Notifications</span></a></li>
        <li><a href="{% url 'saved:index' %}" class="nav-link scrollto"><i class="bx bx-bookmark"></i> <span>Saved Posts</span></a></li>
        <li><a href="{% url 'core:profile' pk=profile %}" class="nav-link scrollto"><i class="bx bx-user"></i>
            <span>Profile</span></a></li>
      </ul>
    </nav>
  </div>

  <div class='footer'>
    <a href="{% url 'core:logout' %}" class="btn-more nav-link"><i class="bx bx-log-out" id="more-btn-logo"></i><span>Logout</span></a>
  </div>
</header>
{% endblock header %}

{% block main %}
<main id="main">
  <section class="inner-page">
    <div>
      <form action="" method="get">
        {% csrf_token %}
        <div class="searchBar">
          <input id="searchQueryInput" type="text" name="searchQueryInput" placeholder="Search" />
          <button id="searchQuerySubmit" type="submit" name="searchQuerySubmit">
            <i class='bx bx-search search-icon' ></i>
          </button>
        </div>
      </form>
    </div>

    <div class="container">
      <div class="search-results-block">
        <p class="search-heading">Search By User</p>
        {% for user in username_profile_list %}
        <div class="result-element">
          <div class="user-data">
            <div class='ava'>
              <img class="image" src="{{user.profile_pic.url}}" style='width: 100%;height: 100%;object-fit: cover;object-position: center;'>
            </div>
            <div class='custom-pad'>
              <p class="user-name">{{user.display_name}}</p>
              <p class="user-username">@{{user.user}}</p>
              <p>{{user.bio|truncatewords:50}}</p>
            </div>
            <div class='profile-link-btn'>
              <a href="{% url 'core:profile' pk=user.user %}"><input id='v-p' type="button" value="Visit Profile"></a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
</main>
{% endblock main %}

Pinscribe Project Assets/ProjectEnv/project_pin/templates/settings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <link rel="stylesheet" href="{% static 'css/temp.css' %}">
</head>
<body>
    <div class="profile">
        <div class="content">
        <h1>Edit Profile</h1>
        <h2>{{temp}}</h2>
        <form method='POST' enctype="multipart/form-data" >
            {% csrf_token %}
            <fieldset>
            <div class="grid-35">
                <label for="avatar">Your Photo</label>
            </div>
            <div class="grid-65">
                <span class="photo" title="Upload your Avatar!">
                    {% if image != None %}
                    <img src="{{image}}" alt="avatar">
                    {% else %}
                    <img src="{% static 'images/default.png' %}" alt="avatar">
                    {% endif %}
                </span>
                <input required type="file" class="btn-up" name='image-up' />
            </div>
            </fieldset>
            <fieldset>
            <div class="grid-35">
                <label for="fname">Name</label>
            </div>
            <div class="grid-65">
                <input required type="text" name='fname' id="fname" tabindex="1" />
            </div>
            </fieldset>
            <fieldset>
            <div class="grid-35">
                <label for="bio">Bio</label>
            </div>
            <div class="grid-65">
                <textarea required name="bio" id="" cols="30" rows="auto" tabindex="3"></textarea>
            </div>
            </fieldset>
            <fieldset class="btns">
            <a class='cancel-btn-link' href="{% url 'core:profile' pk=user_profile.user.username %}"><input type="button" name='cancel' class="btn cancel" value="Cancel" /></a>
            <input type="submit" class="btn" value="Save Changes" />
            </fieldset>
    
        </form>
        </div>
    </div>
</body>
</html>

Pinscribe Project Assets/ProjectEnv/project_pin/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SignUp</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login_and_signup_form.css' %}">
    <script src="{% static 'js/login.js' %}"></script>
</head>
<body id="gradient">
    <div class="form-container">
        <form action="" method="post" class="">
            {% csrf_token %}
            <div class="logo-container">
                <p>WELCOME TO 
                    <img src="{% static 'images/logo-text.png' %}" alt="logo">
                </p>
            </div>
            <div class="input-container">
                {% for message in messages %}
                <h5>{{message}}</h5>
                {% endfor %}
                <label for="username">Username</label>
                <input required type="text" name="username" placeholder="Enter your username... ">

                <label for="email">Email</label>
                <input  required type="email" name="email" id="" placeholder="Enter your email...">

                <label for="password1">Password</label>
                <input required type="password" name="password1" id="" placeholder="Enter your password...">

                <label for="password2">Confirm Password</label>
                <input required type="password" name="password2" id="" placeholder="Confirm your password...">
                <a href="{% url 'core:login' %}">Already a user? Login</a>
            </div>
            
            <div class="btn-container">
                <input type="submit" value="SignUp" class="btn">
            </div>
            
        </form>
    </div>

</body>
</html>

Pinscribe Project Assets/ProjectEnv/project_pin/templates/upload.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>

    <link rel="stylesheet" href="{% static 'css/upload.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">

</head>
<body>
    {% for message in messages %}
    <marquee behavior="alternate" direction="right" Scrollamount=8><p id='alert-msg'>{{message}}</p></marquee>
    {% endfor %}
    <a href="{% url 'core:index' %}"><button class='btn-back'><i class='bx bx-left-arrow-alt'></i></button></a>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class='post-form-block'> 
            <div class='content'>
                <div class="temp">
                    <input type="file" class="up-btn" name="post_image" >
                    <p>Recommended resolution: 800x800px</p>
                </div>
                <div class='caption-section'>
                    <div class='user-data'>
                        <img src="{{user_profile.profile_pic.url}}" class="img-fluid img-thumbnail mt-4 mb-2">
                        <a href="{% url 'core:profile' pk=user_profile.user.username %}">
                            <p>{{user_profile.display_name}}</p>
                            <br>
                            <span>@{{user_profile.user.username}}</span>
                        </a>
                    </div>
                    <textarea name="caption" id="" cols="25" rows="10" placeholder="Enter post description ..."></textarea>
                    <input type="submit" value='Post' class="upload-btn">
                </div>
            </div>
        </div>
    </form>
</body>
</html>